### ISSUE TITLE
prependUnicode is doesn't work at the second call

### ISSUE THREAD

**Issue by inna-rist** [nfroidure/gulp-svgicons2svgfont#40]
Hi everybody,
i use build from the iconfont gulp iconfont and svgicons2svgfont. My gulp task looks like this:
```
// Task for iconfont
var runTimestamp = Math.round(Date.now()/1000);

gulp.task('iconfont', function(){
  return gulp.src(options.src.svgIcons)
    .pipe(iconfont({
        fontName: 'IconFont', // required
        prependUnicode: true, // recommended option
        formats: ['ttf', 'eot', 'woff'], // default, 'woff2' and 'svg' are available
        timestamp: runTimestamp, // recommended to get consistent builds when watching files
        normalize: true,
        fontHeight: 1001
    }))
    .pipe(gulp.dest(options.src.font));
});
```
Everything works wonderfully on the first call.
On the second call, after a new icon has been added, the wrong unicode will be assigned to the new icon. Always the first unicode (standard uea01). The following error message can be seen on the console:
```
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: The unicode codepoint of the glyph cross seems to be already used by another glyph.
```

Can someone help me here?
Is that a bug or is there already a solution?

Thanks.

**Comment by NaridaL** [comment]
Also, have you seen https://github.com/nfroidure/gulp-iconfont/issues/72#issuecomment-209261304 ? Could be related.

**Comment by martingregoire** [comment]
@NaridaL we have the same problem. I added a demo repository, please have a look: https://github.com/martingregoire/gulp-svgicons2svgfont-issue

So when adding a new icon file to a folder which contains icon files which were processed before, and were renamed to contain the unicode codepoint in the filename, we cannot add a new icon. This is explained better and with an example in the linked demo README file.

I believe this is due to the changes in 0bc1debf637f68474a44f72aa3954184494d1dbe. Why was this sorting feature removed, could you please have a look?

We will revert to version 4.0.2 for now.

**Comment by NaridaL** [comment]
Hi @martingregoire thanks for the very detailed problem description! IIRC the feature was removed because it kind of defeated the purpose of the stream processing, as all files needed to be loaded so they could be sorted. I'll have a look if there's a better solution.

**Comment by abstractic** [comment]
I also have the same issue, i.e. if I will copy a new icon into the folder with SVG files and then executes my gulp task to include it to my font file, I'll get the same error. It worked fine with gulp-iconfont version 9.1.0.

**Comment by NaridaL** [comment]
OK, gulp really doesn't like you renaming the files in a plugin, so I've refactored it to be a replacement for gulp.src instead of a transforming plugin. There I am free to rename files as I wish. (See also https://github.com/gulpjs/gulp/issues/744). This has the downside that you can't pipe files which were previously modified/generated by gulp to this plugin anymore. I'm not sure how much of a problem that is. Let me know if this is a problem for you.

Instead of piping the result of gulp.src to this plugin, you should now pass the globs as the first parameter. The options are passed as the same parameter: Here is the modified example of @martingregoire, using gulp-svgicons2svgfont@6.0.0: 
```
gulp = require("gulp");
var svgicons2svgfont = require("gulp-svgicons2svgfont");

gulp.task("Iconfont", function() {
  svgicons2svgfont(["icons/*.svg"], {
    fontName: "myfont",
    prependUnicode: true
  })
    .on("glyphs", function(glyphs) {
      console.log(glyphs);
      // Here generate CSS/SCSS  for your glyphs ...
    })
    .pipe(gulp.dest("./"));
});
```

**Comment by martingregoire** [comment]
Thanks @NaridaL!

> This has the downside that you can't pipe files which were previously modified/generated by gulp to this plugin anymore.

This is not a problem for our use case, we pass the source icon files directly to this plugin.

I tried upgrading the example to gulp-svgicons2svgfont@6.0.0, but now I get an error when running the gulp task. Do you have an idea what I'm doing wrong?

These are my changes to the example repo:

```diff
diff --git a/package.json b/package.json
index 3897f73..ba862c2 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
   "author": "",
   "license": "MIT",
   "devDependencies": {
-    "gulp-svgicons2svgfont": "^5.0.1"
+    "gulp-svgicons2svgfont": "^6.0.0"
   },
   "dependencies": {
     "gulp": "^3.9.1"

diff --git a/Gulpfile.js b/Gulpfile.js
index 67636fe..0bf7a32 100644
--- a/Gulpfile.js
+++ b/Gulpfile.js
@@ -2,14 +2,10 @@ gulp = require('gulp');
 var svgicons2svgfont = require('gulp-svgicons2svgfont');
 
 gulp.task('Iconfont', function() {
-  gulp
-    .src(['icons/*.svg'])
-    .pipe(
-      svgicons2svgfont({
-        fontName: 'myfont',
-        prependUnicode: true,
-      }),
-    )
+    svgicons2svgfont(['icons/*.svg'], {
+      fontName: 'myfont',
+      prependUnicode: true,
+    })
     .on('glyphs', function(glyphs) {
       console.log(glyphs);
       // Here generate CSS/SCSS  for your glyphs ...
```

Then when executing:

```shell
$ npm i
$ gulp Iconfont
```

The file `icons/arrow-down.svg` is renamed to `icons/uEA01-arrow-down.svg`, and `icons/arrow-up.svg` to `icons/uEA02-arrow-up.svg`, and this error message comes up:

```shell
$ gulp Iconfont                                         
[12:47:45] Using gulpfile gulp-svgicons2svgfont-issue/Gulpfile.js
[12:47:45] Starting 'Iconfont'...
[12:47:45] Finished 'Iconfont' after 7.89 ms
gulp-svgicons2svgfont-issue/node_modules/vinyl/index.js:233
      throw new Error('No path specified! Can not get relative.');
      ^

Error: No path specified! Can not get relative.
    at File.get (gulp-svgicons2svgfont-issue/node_modules/vinyl/index.js:233:13)
    at DestroyableTransform.saveFile [as _transform] (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/lib/dest/index.js:36:49)
    at DestroyableTransform.Transform._read (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (gulp-svgicons2svgfont-issue/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Readable.ondata (gulp-svgicons2svgfont-issue/node_modules/gulp-svgicons2svgfont/node_modules/readable-stream/lib/_stream_readable.js:662:20)
    at emitOne (events.js:116:13)
    at Readable.emit (events.js:211:7)
```

**Comment by nfroidure** [comment]
Probably that to solve this issue in the "gulp spirit" would be to split the module into 2 parts, one to rename files and another to generate the font. Giving something like:
```
gulp.src(...)
  .pipe(prefixIcons())
  .pipe(gulp.dest( ...))
  .pipe(svgIconsToSVGFont())
  .pipe(gulp.dest( ...))
```

Not using gulp anymore but decided to spend some time fixing the gulp5 comptatibility of the whole gulp-iconfont dependencies. Before I proceed could you tell me what you think of it and if you're still using it? @NaridaL @abstractic  @martingregoire  @inna-rist

**Comment by martingregoire** [comment]
@nfroidure the project using this package has been archived in the meantime, so no, not using it any longer.
